services:
  # Backend Service (Node.js)
  - type: web
    name: backend-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-database
          property: connectionString

  # Frontend Service (React)
  - type: web
    name: frontend-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build

# MongoDB Database
databases:
  - name: mongodb-database
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all connections from render services

# Note: Removed unsupported fields like publishDir and routes
