services:
  # Backend Service (Node.js)
  - type: web
    name: server
    env: node
    plan: free
    root: server
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-database
          property: connectionString

  # Frontend Service (React)
  - type: web
    name: client
    env: node
    plan: free
    root: client
    buildCommand: npm install
    startCommand: npm start

# MongoDB Database
databases:
  - name: mongodb-database
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all connections from render services

# Note: Removed unsupported fields like publishDir and routes
