services:
  # Backend Service (Node.js)
  - type: web
    name: backend-service
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-database
          property: connectionString

  # Frontend Service (React)
  - type: web
    name: frontend-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    # Or if using a different start command, replace with your specific command
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# MongoDB Database
databases:
  - name: mongodb-database
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all connections from render services

# Deployment Notes:
# 1. Changed "static" type to "web" for frontend service
# 2. Added npx serve to serve the built React app
# 3. Ensure your frontend has a build script that generates a 'build' directory
# 4. You may need to adjust the startCommand based on your specific project setup
